# Generated by Django 6.0.5 on 2026-05-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=10, unique=True)),
                ("route_number", models.IntegerField()),
                ("route_name", models.CharField(max_length=200)),
                ("yatayat_id", models.IntegerField()),
                ("yatayat_name", models.CharField(max_length=200)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("alt_names", models.CharField(blank=True, max_length=200, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_sequence", models.IntegerField()),
                ("direction", models.CharField(default="forward", max_length=20)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="bus.route",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_routes",
                        to="bus.stop",
                    ),
                ),
            ],
            options={
                "ordering": ["stop_sequence"],
            },
        ),
    ]
